=== HuangZhiBin/Petral-UI/Example/Petral/petral-ui.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:group name="viewGroup">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="view" />
                <xs:element ref="UIView" />
                <xs:element ref="button" />
                <xs:element ref="UIButton" />
                <xs:element ref="imageview" />
                <xs:element ref="UIImageView" />
                <xs:element ref="label" />
                <xs:element ref="UILabel" />
                <xs:element ref="scrollview" />
                <xs:element ref="UIScrollView" />
                <xs:element ref="tableview" />
                <xs:element ref="UITableView" />
                <xs:element ref="textfield" />
                <xs:element ref="UITextField" />
                <xs:element ref="textview" />
                <xs:element ref="UITextView" />
                <xs:element ref="collectionview" />
                <xs:element ref="UICollectionView" />
                <xs:element ref="datepicker" />
                <xs:element ref="UIDatePicker" />
                <xs:element ref="pickerview" />
                <xs:element ref="UIPickerView" />
                <xs:element ref="progressview" />
                <xs:element ref="UIProgressView" />
                <xs:element ref="searchbar" />
                <xs:element ref="UISearchBar" />
                <xs:element ref="segmentedcontrol" />
                <xs:element ref="UISegmentedControl" />
                <xs:element ref="slider" />
                <xs:element ref="UISlider" />
                <xs:element ref="stepper" />
                <xs:element ref="UIStepper" />
                <xs:element ref="switch" />
                <xs:element ref="UISwitch" />
                <xs:element ref="webview" />
                <xs:element ref="UIWebView" />
                <xs:element ref="flexview" />
            </xs:choice>

        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="attributeAttr">
        <xs:attribute name="p-show" type="xs:string" />
        <xs:attribute name="id" type="xs:string" />
        <xs:attribute name="frame" type="xs:string" />
        <xs:attribute name="backgroundColor" type="xs:string" />
        <xs:attribute name="borderColor" type="xs:string" />
        <xs:attribute name="borderWidth" type="xs:string" />
        <xs:attribute name="borderRadius" type="xs:string" />
        <xs:attribute name="shadowColor" type="xs:string" />
        <xs:attribute name="shadowOpacity" type="xs:string" />
        <xs:attribute name="shadowRadius" type="xs:string" />
        <xs:attribute name="shadowOffset" type="xs:string" />
        <xs:attribute name="masksToBounds" type="xs:string" />
        <xs:attribute name="clipsToBounds" type="xs:string" />
    </xs:attributeGroup>

    <xs:attributeGroup name="restraintAttr">
        <xs:attribute name="left" type="xs:string" />
        <xs:attribute name="right" type="xs:string" />
        <xs:attribute name="top" type="xs:string" />
        <xs:attribute name="bottom" type="xs:string" />
        <xs:attribute name="xCenter" type="xs:string" />
        <xs:attribute name="yCenter" type="xs:string" />
        <xs:attribute name="center" type="xs:string" />
        <xs:attribute name="width" type="xs:string" />
        <xs:attribute name="height" type="xs:string" />
    </xs:attributeGroup>

    <xs:element name="button">
        <xs:complexType>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="font" type="xs:string" />
            <xs:attribute name="titleColor" type="xs:string" />
            <xs:attribute name="backgroundColorHighlighted" type="xs:string" />
            <xs:attribute name="backgroundImage" type="xs:string" />
            <xs:attribute name="backgroundImageHighlighted" type="xs:string" />
            <xs:attribute name="title" type="xs:string" />
            <xs:attribute name="align" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UIButton" substitutionGroup="button"></xs:element>

    <xs:element name="imageview">
        <xs:complexType>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="image" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UIImageView" substitutionGroup="imageview"></xs:element>

    <xs:element name="label">
        <xs:complexType>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="font" type="xs:string" />
            <xs:attribute name="textColor" type="xs:string" />
            <xs:attribute name="text" type="xs:string" />
            <xs:attribute name="align" type="xs:string" />
            <xs:attribute name="lines" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UILabel" substitutionGroup="label"></xs:element>

    <xs:element name="textfield">
        <xs:complexType>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="font" type="xs:string" />
            <xs:attribute name="textColor" type="xs:string" />
            <xs:attribute name="text" type="xs:string" />
            <xs:attribute name="placeholder" type="xs:string" />
            <xs:attribute name="align" type="xs:string" />
            <xs:attribute name="isSecureText" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UITextField" substitutionGroup="textfield"></xs:element>

    <xs:element name="textview">
        <xs:complexType>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="font" type="xs:string" />
            <xs:attribute name="textColor" type="xs:string" />
            <xs:attribute name="text" type="xs:string" />
            <xs:attribute name="align" type="xs:string" />
            <xs:attribute name="isEditable" type="xs:string" />
            <xs:attribute name="contentSize" type="xs:string" />
            <xs:attribute name="contentOffset" type="xs:string" />
            <xs:attribute name="contentInset" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UITextView" substitutionGroup="textview"></xs:element>


    <xs:element name="datepicker" substitutionGroup="view"></xs:element>
    <xs:element name="UIDatePicker" substitutionGroup="datepicker"></xs:element>

    <xs:element name="pickerview" substitutionGroup="view"></xs:element>
    <xs:element name="UIPickerView" substitutionGroup="pickerview"></xs:element>

    <xs:element name="progressview" substitutionGroup="view"></xs:element>
    <xs:element name="UIProgressView" substitutionGroup="progressview"></xs:element>

    <xs:element name="searchbar" substitutionGroup="view"></xs:element>
    <xs:element name="UISearchBar" substitutionGroup="searchbar"></xs:element>

    <xs:element name="segmentedcontrol" substitutionGroup="view"></xs:element>
    <xs:element name="UISegmentedControl" substitutionGroup="segmentedcontrol"></xs:element>

    <xs:element name="slider" substitutionGroup="view"></xs:element>
    <xs:element name="UISlider" substitutionGroup="slider"></xs:element>

    <xs:element name="stepper" substitutionGroup="view"></xs:element>
    <xs:element name="UIStepper" substitutionGroup="stepper"></xs:element>

    <xs:element name="switch" substitutionGroup="view"></xs:element>
    <xs:element name="UISwitch" substitutionGroup="switch"></xs:element>

    <xs:element name="webview" substitutionGroup="view"></xs:element>
    <xs:element name="UIWebView" substitutionGroup="webview"></xs:element>

    <xs:element name="scrollview">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="contentSize" type="xs:string" />
            <xs:attribute name="contentOffset" type="xs:string" />
            <xs:attribute name="contentInset" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UIScrollView" substitutionGroup="scrollview"></xs:element>

    <xs:element name="tableview">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="header" minOccurs="0" maxOccurs="1" />
                <xs:element ref="footer" minOccurs="0" maxOccurs="1" />
                <xs:element ref="section-header" minOccurs="0" maxOccurs="1" />
                <xs:element ref="section-footer" minOccurs="0" maxOccurs="1" />
                <xs:element ref="cell" minOccurs="1" maxOccurs="1" />
            </xs:choice>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
            <xs:attribute name="p-rows" type="xs:string" />
            <xs:attribute name="p-sections" type="xs:string" />
            <xs:attribute name="contentSize" type="xs:string" />
            <xs:attribute name="contentOffset" type="xs:string" />
            <xs:attribute name="contentInset" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UITableView" substitutionGroup="tableview"></xs:element>
    <xs:element name="header">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:element name="footer">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:element name="section-header">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:element name="section-footer">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:element name="cell">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>

    <xs:element name="collectionview" substitutionGroup="scrollview"></xs:element>
    <xs:element name="UICollectionView" substitutionGroup="collectionview"></xs:element>

    <xs:element name="flexview">
        <xs:complexType>
            <!-- <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" /> -->
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element ref="template" />
            </xs:sequence>
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="attributeFlexviewAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:element name="template">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attributeFlexviewAttr">
        <xs:attribute name="p-item-count" type="xs:string" />
        <xs:attribute name="p-direction" type="xs:string" />
        <xs:attribute name="p-padding" type="xs:string" />
        <xs:attribute name="p-item-space-x" type="xs:string" />
        <xs:attribute name="p-item-space-y" type="xs:string" />
    </xs:attributeGroup>

    <xs:element name="view">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
            <xs:attributeGroup ref="attributeAttr" />
            <xs:attributeGroup ref="restraintAttr" />
        </xs:complexType>
    </xs:element>
    <xs:element name="UIView" substitutionGroup="view"></xs:element>


    <xs:element name="views">
        <xs:complexType>
            <xs:group ref="viewGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:complexType>
        <xs:unique name="idUnique">
            <xs:selector xpath=".//*" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>
</xs:schema>

=== HuangZhiBin/Petral-UI/Example/Petral/DataFlexViewController.xml
<?xml version="1.0" encoding="utf-8" ?>
<views xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://github.com/HuangZhiBin/Petral-UI/raw/2.2.0/Example/Petral/petral-ui.xsd">
    <view left="0" right="0" top="0" bottom="0" backgroundColor="white">
        <scrollview id="scrollview" left="0" top="64" width="100%" bottom="70" backgroundColor="yellow">
            <flexview id="flexview" width="100%" p-direction="column">
                <template width="100%" backgroundColor="#f9f9f9">
                    <imageview id="cellImage" width="50" height="50" left="10" yCenter="0"></imageview>
                    <label id="cellLabel" yCenter="0" height="20" font="14" textColor="#333333" left="cellImage;10" right="10"></label>
                    <view id="line" height="1" width="100%" bottom="0" backgroundColor="#d8d8d8"></view>
                </template>
            </flexview>
        </scrollview>
        <button id="changeBtn" title="切换数据" backgroundColor="#16a051" backgroundColorHighlighted="#83b001" bottom="10" masksToBounds="true" cornerRadius="6" height="44" xCenter="0" width="90%" />
    </view>
</views>

=== HuangZhiBin/Petral-UI/Example/Petral/XmlViewController.xml
<?xml version="1.0" encoding="utf-8" ?>
<views xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.koudaikr.cn/petral-ui.xsd">
    <view left="0" right="0" top="0" bottom="0" backgroundColor="green">
        <imageview id="image1" frame="150,20,50,50" backgroundColor="#777777" shadowColor="#880000" shadowOpacity="0.95" shadowRadius="20" shadowOffset="2,5" borderColor="#888888" borderWidth="0" masksToBounds="true" borderRadius="12.5" image="setting"></imageview>
        
        <imageview id="image11" frame="210,20,50,50" backgroundColor="#777777" shadowColor="#880000" shadowOpacity="0.95" shadowRadius="20" shadowOffset="2,5" borderColor="#888888" borderWidth="0" masksToBounds="true" borderRadius="12.5" image="setting"></imageview>
        
        <label id="label1" frame="10,50,100,20" font="18" textColor="#555555" backgroundColor="#d3d3d3" text="发送短信通知功能" lines="1" align="right" top="image1;0" height="image1,0"></label>
        
        <textview id="textview1" frame="10,200,300,40" contentInset="10,10,10,10" backgroundColor="#f5f5f5" font="13" textColor="#000000" text="HIMYM" align="left" isEditable="false"></textview>
        
        <textfield id="textfield1" frame="10,260,300,40" backgroundColor="#f8f8f8" font="13+" textColor="#888888" text="default" placeholder="    this is placeholder   " align="left" isSecureText="false"></textfield>
        
        <button id="button1" frame="10,320,300,40" font="13+" titleColor="#555555" backgroundColor="#d6d6d6" backgroundColorHighlighted="#c8c8c8" backgroundImage="setting" backgroundImageHighlighted="setting2" title="Click" align="center"></button>
        
        <RedImageView p-show="{showRed}" id="image2" frame="250,120,50,50" image="setting" top="button1" left="button1;5"></RedImageView>
        
        <scrollview id="scrollview1" frame="10,370,300,120" contentSize="300,120" contentOffset="0,0" contentInset="10,20,10,10" backgroundColor="#d6d6d6">
            <label id="label1" frame="300,120" font="12" textColor="#ffffff" backgroundColor="#912300" text="   通过直接调用.为前缀的方法，直接连续设置 View 的 UI 属性，与调用系统方法的 API 类似。" lines="13" align="right" width="50%" height="50%"></label>
        </scrollview>
        <tableview id="tableview1" frame="10,500,300,120" backgroundColor="#d6d6d6"></tableview>
        
        <scrollview p-show="{showManyView}" left="0" top="20" width="100%" height="120" contentSize="{time}00,120" backgroundColor="orange">
            <manyview id="manyview" height="100%" width="1000" p-times="{time}" p-item-size="100,120" p-direction="row">
                <template>
                    <view width="100%" height="100%" backgroundColor="blue">
                        <imageview id="cellIcon" width="50" height="50" xCenter="0" top="20" image="setting"></imageview>
                        <label id="cellInfo" xCenter="0" width="80%" height="20" font="14" textColor="#ffffff" top="cellIcon;10" text="cell" align="center"></label>
                    </view>
                </template>
            </manyview>
        </scrollview>
        
        <manyview id="flexView1" frame="0,100,280,580" backgroundColor="purple" p-times="{time2}" p-item-size="280,240" p-direction="column" p-padding="0,0,0,0" p-item-space-x="10" p-item-space-y="1">
            <template>
                <manyview id="flexView2" width="100%" height="100%" backgroundColor="orange" p-times="3" p-item-size="100,100" p-direction="wrap" p-padding="10,20,30,40" p-item-space-x="10" p-item-space-y="5">
                    <template>
                        <view width="100%" height="100%" backgroundColor="blue">
                            <label id="cellLabel" frame="50,0,50,20" font="14" textColor="#555555" backgroundColor="#d3d3d3" text="发送" lines="1" align="left"></label>
                            <imageview id="cellImage" frame="20,30,50,50" image="setting"></imageview>
                            <view left="0" top="0" width="40%" height="40%" backgroundColor="green">
                                <imageview id="cellLabel2" frame="0,0,40,40" image="setting"></imageview>
                            </view>
                            <manyview id="flexView3" p-show="true" frame="50,20,50,80" backgroundColor="purple" p-times="5" p-item-size="20,20" p-direction="wrap" p-padding="0,0,0,0" p-item-space-x="10" p-item-space-y="5">
                                <template>
                                    <imageview id="subImage" frame="0,0,20,20" image="setting"></imageview>
                                    <label id="subLabel" frame="0,0,20,20" font="7" textColor="#ffffff" text="abc" lines="1" align="center"></label>
                                </template>
                            </manyview>
                        </view>
                    </template>
                </manyview>
            </template>
        </manyview>
        
        <UserInfoView id="userInfoView" frame="0,0,0,120" right="20" left="20" top="180" backgroundColor="#dd7700" clipsToBounds="true" data='{"text":"{element}"}'>
            <imageview id="image55" frame="0,0,50,50" image="setting"></imageview>
        </UserInfoView>
        
    </view>
</views>

=== HuangZhiBin/Petral-UI/Example/Petral/SectionListViewController.xml
<?xml version="1.0" encoding="utf-8" ?>
<views xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.koudaikr.cn/org/petral-ui.xsd">
    <view left="0" right="0" top="0" bottom="0" backgroundColor="white">
        <tableview id="tableview1" left="0" top="0" width="100%" height="100%" backgroundColor="#d6d6d6" p-sections="2" p-rows="3">
            <header height="60" backgroundColor="yellow">
                <label id="headerLabel" width="100%" height="20" center="0" text="this is header" align="center" />
            </header>
            <section-header height="30" backgroundColor="blue">
                <label id="sectionHeaderLabel" width="100%" height="20" center="0" text="this is section header" align="center" textColor="white" />
            </section-header>
            <section-footer height="20" backgroundColor="red">
                <label id="sectionFooterLabel" width="100%" height="20" center="0" text="this is section footer" align="center" />
            </section-footer>
            <cell height="80">
                <imageview id="cellImage" image="setting" width="50" height="50" left="15" yCenter="0" />
                <label id="cellLabel" left="cellImage;15" right="15" height="20" top="cellImage" text="this is cell text" />
                <label id="cellSubLabel" left="cellImage;15" right="15" height="20" top="cellLabel;10" text="this is cell sub text" />
            </cell>
            <footer height="60" backgroundColor="orange">
                <label id="footerLabel" width="100%" height="20" center="0" text="this is footer" align="center" />
            </footer>
        </tableview>
    </view>
</views>
